### ISSUE TITLE
branch libev: testing results

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#190]
I'm testing knxd from branch libev compiled with default config and without libev subdir, current release is 0.12.0~3. knxd is started on the shell with -i -D -T -S -b ipt:192.168.1.20. On 192.168.1.20 runs knxd with release 0.11.9.
Results:
"knxtool vbusmonitor1 ip:localhost" runs OK, but only for a while. After some time the remote knxd does not send anything into the tunnel anymore. tcpdump proves, there is no traffic anymore.
"knxtool groupswrite ip:localhost 1/0/12 1" shows up in the local bus monitor but nothing is sent into the tunnel. I got the impression that with new libev nothing was ever sent into the tunnel.

Doing the same tests with current master 0.11.15 all this runs perfectly fine.

**Comment by smurfix** [comment]
Thanks for the report, will test.

**Comment by smurfix** [comment]
Should work now. Please test.

**Comment by tru7** [comment]
Unfortunately the problems persist with release 0.12.0~6

When knxd is started, the tunnel is opened as seen in tcpdump like this:
19:38:50.316310 IP 192.168.1.21.3672 > 192.168.1.20.3671: UDP, length 26
19:38:50.317820 IP 192.168.1.20.3671 > 192.168.1.21.3672: UDP, length 20
While this communication is repeated exactly every 30s with master and stable - nothing is sent from local knxd-libev anymore. After one or two minutes the remote knxd stops sending into the tunnel, probably because it's considers dead.
A command with groupswrite is seen in the local busmonitor but nothing is ever sent into the tunnel to the remote knxd.

**Comment by tru7** [comment]
Better with release 0.12.0~7 but still some major problem

Now I see telegrams sent into the tunnel from local knxd. They are also acknoledged from the remote knxd.
But still no "keep-alive" traffic which can be seen with stable and master. Therefore after 1 to 2 minutes the remote knxd stops sending. Also telegrams from local knxd don't get accepted by the remote knxd anymore and therefore don't make it to the bus anymore.
So the tunnel is invalidated from the remote side after these 1 to 2 minutes.

**Comment by tru7** [comment]
Now it works with the latest commits for 0.12.0~7: there is now a keep-alive every 30 seconds from the local knxd for the tunnel it opened and therefore the remote knxd keeps sending bus traffic. So updates from the local knxd can be sent and are accepted by the remote knxd at any time.
Yippee, first working knxd-libev for me! Now watching longterm stability.

**Comment by smurfix** [comment]
Good to hear.
I hope to get ETS5 support up&running tomorrow; routing of individually-addressed packets is broken at the moment.

**Comment by tru7** [comment]
Version 0.12.0~8 still working OK for me

**Comment by tru7** [comment]
I very much like knxd 0.12.0

**Comment by smurfix** [comment]
Good. So do I. Goodbye pthsem, you'll not be missed. My only regret is that the deadline for Debian Stretch is … last week.

**Comment by JoeRu** [comment]
Hi all,
i did test - and compiling and installation worked like a charm. But:
knxd only listen on IPv6 - and did not bind to ipv4?

systemd    1 root   47u  IPv6  12909      0t0  TCP *:6720 (LISTEN)
knxd    1250 knxd    4u  IPv6  12909      0t0  TCP *:6720 (LISTEN)

an lsof -i 4 does not show any knxd activities or anything. I switch ipv6 of and rebooted but the behaviour stays.

Do i forget anything?
Startup of knxd is fine - knxtool does not seem to work so. no connection.
Joe

**Comment by smurfix** [comment]
On 12.01.2017 00:09, JoeRu wrote:
>
> Hi all,
> i did test - and compiling and installation worked like a charm. But:
> knxd only listen on IPv6 - and did not bind to ipv4?
>
That's normal behavior of systemd and not a bug. The socket answers to both.

> Do i forget anything?
Your actual knxd command line?
>
> Startup of knxd is fine - knxtool does not seem to work
>
Your actual knxtool command line?

-- 
-- Matthias Urlichs

**Comment by JoeRu** [comment]
Hi Matthias,

ok. Then maybe this error-message due installation is the problem:
`
root@openHAB:/home/joe/knxd012/012# dpkg -i knxd_*.deb knxd-tools_*.deb
(Lese Datenbank ... 143382 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von knxd_0.12.0-1_amd64.deb ...
Entpacken von knxd (0.12.0-1) über (0.12.0-1) ...
Vorbereitung zum Entpacken von knxd-tools_0.12.0-1_amd64.deb ...
Entpacken von knxd-tools (0.12.0-1) über (0.12.0-1) ...
knxd (0.12.0-1) wird eingerichtet ...
addgroup: Die Gruppe »knxd« existiert bereits als Systemgruppe. Programmende.
Warnung: Das von Ihnen angegebene Home-Verzeichnis /var/lib/knxd existiert bereits.
Der Systembenutzer »knxd« existiert bereits. Programmende.
**Job for knxd.socket failed. See "systemctl status knxd.socket" and "journalctl -xe" for details.
knxd.socket couldn't start.**
knxd-tools (0.12.0-1) wird eingerichtet ...
Trigger für systemd (229-4ubuntu12) werden verarbeitet ...
Trigger für ureadahead (0.100.0-19) werden verarbeitet ...
Trigger für libc-bin (2.23-0ubuntu4) werden verarbeitet ...
`

This is my knxd.conf
`KNXD_OPTS="-e 2.2.20 -DTS -b ipt:192.168.178.57"`

This installation error persist even when i use
`dpkg -r knxd knxd-tools`
 ahead of it.

The Status
```
systemctl status knxd.socket
● knxd.socket
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead) since Do 2017-01-12 00:12:36 CET; 8h ago

Jan 12 08:39:42 openHAB systemd[1]: knxd.socket: Socket service knxd.service already active, refusing.
Jan 12 08:39:42 openHAB systemd[1]: Failed to listen on KNX Daemon (socket).
Jan 12 08:40:03 openHAB systemd[1]: Closed KNX Daemon (socket).
```

`systemctl stop knxd.service` has no effect.
Even so - the service starts after installation

```
root@openHAB:/home/joe/knxd012/012# systemctl status knxd.service
● knxd.service - KNX Daemon
   Loaded: loaded (/lib/systemd/system/knxd.service; enabled; vendor preset: enabled)
   Active: active (running) since Do 2017-01-12 08:43:56 CET; 3min 30s ago
 Main PID: 20641 (knxd)
   CGroup: /system.slice/knxd.service
           └─20641 /usr/bin/knxd -e 2.2.20 -DTS -b ipt:192.168.178.57

Jan 12 08:43:56 openHAB systemd[1]: Starting KNX Daemon...
Jan 12 08:43:56 openHAB systemd[1]: Started KNX Daemon.
Jan 12 08:43:56 openHAB systemd[1]: Started KNX Daemon.
```


My test with knxtool:
```
root@openHAB:/home/joe/knxd012/012# knxtool groupwrite ip:localhost 1/0/0 1
Open failed: Connection refused
```

Same error (no connection) goes on the dedicated ip and the default setting i used with 0.10 with openHab.
   
So - thats where i actualy are stucked.
knxd starts - but no connection is possible.

joe

**Comment by smurfix** [comment]
On 12.01.2017 08:55, JoeRu wrote:
> |● knxd.socket Loaded: masked (/dev/null; bad)|
So you disabled knxd.socket at some time in the past, with "systemctl
mask knxd.socket".
You shouldn't be surprised when it doesn't start then. :-P

systemctl unmask knxd.socket

systemctl stop knxd

systemctl start knxd.socket

systemctl start knxd

… should fix this.


-- 
-- Matthias Urlichs

**Comment by JoeRu** [comment]
yeah - ok - seems to be not my time around 0:0
 - now this error is gone. 
Still, i can't connect to knxd via knxtool 
- funny so ETS4 connects via IBNetRouter  - and this works very well - 
but the eibnetIP is still refusing connection.

Working - eibnetRouter
```
➜  ~ sudo nmap --script knx-gateway-discover -e en0 192.168.178.1/24

Starting Nmap 7.12 ( https://nmap.org ) at 2017-01-12 10:57 CET
Pre-scan script results:
| knx-gateway-discover: 
|   192.168.178.93: 
|     Body: 
|       HPAI: 
|         Port: 3671
|       DIB_DEV_INFO: 
|         KNX address: 2.2.19
|         Decive serial: 010203040506
|         Multicast address: 224.0.23.12
|         Device MAC address: 08:00:27:74:fd:ec
|         Device friendly name: knxd\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
|       DIB_SUPP_SVC_FAMILIES: 
|         KNXnet/IP Core version 1
|         KNXnet/IP Tunnelling version 1
|_        KNXnet/IP Routing version 1

```
A manual
 knxd -t1023 -e 2.2.19 -E 2.2.20:1 -n knxd2 -D -T --Server -b ipt:192.168.178.57
starts the knx daemon - but not seems to open a socket/port.

**Comment by JoeRu** [comment]
Tiny steps - a reboot took it a step ahead.
Now it takes at least on command - and afterwards it resets connections.

root@openHAB:~# knxtool groupswrite ip:192.168.178.93 1/0/0 1
Connect failed: Connection reset by peer
root@openHAB:~# service knxd restart
root@openHAB:~# knxtool groupswrite ip:192.168.178.93 1/0/0 1
Send request
root@openHAB:~# knxtool groupswrite ip:192.168.178.93 1/0/0 0
Connect failed: Connection reset by peer

**Comment by smurfix** [comment]
On 12.01.2017 11:13, JoeRu wrote:
>
> A manual
> knxd -t1023 -e 2.2.19 -E 2.2.20:1 -n knxd2 -D -T --Server -b
> ipt:192.168.178.57
> starts the knx daemon - but not seems to open a socket/port.
>
Well, of course not. There are no arguments which tell it to do so,
because that is done by the knxd.socket file.

If you want to run it manually you need to stop knxd.socket and add -u
and -i options (or leave systemd alone and use "-u /tmp/knxtest" here,
"local:/tmp/knxtest" in knxtool).

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
On 12.01.2017 11:21, JoeRu wrote:
>
> root@openHAB:# knxtool groupswrite ip:192.168.178.93 1/0/0 1
> Send request
> root@openHAB:# knxtool groupswrite ip:192.168.178.93 1/0/0 0
> Connect failed: Connection reset by peer
>
That looks like a bad crash. Could you turn on logging (-t 1023), run
knxd manually, post the last couple of lines?

I'd recommend valgrind but that doesn't work too well on ARM (which I
assume you're using).

-- 
-- Matthias Urlichs

**Comment by JoeRu** [comment]
now i did restart from console with
knxd -t1023 -e 2.2.19 -u /tmp/knxtest -i -E 2.2.20:1 -n knxd2 -D -T
--Server -b ipt:192.168.178.57

The connection via local:/tmp/knxtest results in this output

root@openHAB:~# knxtool groupswrite local:/tmp/knxtest 1/0/0 1
Connect failed: Connection reset by peer

knxd2: Layer 8 [ 4:inet               298.678] New Connection
knxd2: Layer 8 [ 4:inet               298.679] ClientConnection Init
knxd2: Layer 3 [ 3:layer3             298.679] Allocate: falling back to
2.2.19
knxd2: Layer 8 [10:inet               298.679] SendMessage(002): 00 04

exact the same is for IP-connection.
The Messages from knxd doesn't look so bad. But the setting isn't
reproducable on that way.
With systemd the first message works - on commandline part the
Connect failed: Connection reset by peer
shows immidiatly and no reaction on the bus.

No. not ARM. VBOX-Ubuntu. i didn't use valgrind yet.

**Comment by JoeRu** [comment]
ok. knxd is really fuzzy in the order of arguments - i did put -u -i at the end - and now i could reproduce the first ok - second stop thing:

this is the output of knxd - not really any news - when you tell me what i shall to with valgrind - ill follow youre command ;)
```

knxd: Layer 7 [ 8:inet:2.2.20        14.738] OpenGroup
knxd: Layer 4 [ 8:inet:2.2.20        14.738] OpenGroup 1/0/0 WO
knxd: Layer 3 [ 3:layer3             14.738] registerLayer2 8:inet:2.2.20
knxd: Layer 3 [ 3:layer3             14.738] registerLayer2 8:inet:2.2.20 = 1
knxd: Layer 8 [ 7:inet               14.738] SendMessage(002): 00 22
knxd: Layer 7 [ 8:inet:2.2.20        14.738] OpenGroup complete
knxd: Layer 7 [ 7:inet               14.738] recv(002): 00 80
knxd: Layer 4 [ 8:inet:2.2.20        14.738] Send Group T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 9 [ 8:inet:2.2.20        14.738] Enqueue L_Data low from 0.0.0 to 1/0/0 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 3 [ 3:layer3             14.738] RecvData L_Data low from 2.2.20 to 1/0/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 8 [ 2:mcast:knxd         14.738] Send_Route L_Data low from 2.2.20 to 1/0/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 1 [ 2:mcast:knxd         14.738] Send(011): 29 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 2 [ 4:ipt:192.168.178.57 14.738] Send L_Data low from 2.2.20 to 1/0/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 8 [ 7:inet               14.738] ClientConnection 2.2.20 closing
knxd: Layer 3 [ 3:layer3             14.738] Release 2.2.20
knxd: Layer 7 [ 7:inet               14.738] CloseGroup
knxd: Layer 3 [ 3:layer3             14.738] deregisterLayer2 8:inet:2.2.20 = 1
knxd: Layer 3 [ 3:layer3             14.738] deregisterLayer2 8:inet:2.2.20 = 0
knxd: Layer 4 [ 8:inet:2.2.20        14.738] CloseGroup
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.738] SendTunnel(015): 04 17 00 00 11 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.738] Send(015): 04 17 00 00 11 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 0 [ 2:mcast:knxd         14.738] Send(017): 06 10 05 30 00 11 29 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 0 [ 2:mcast:knxd         14.738] Dropped(017): 06 10 05 30 00 11 29 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.738] Send(021): 06 10 04 20 00 15 04 17 00 00 11 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.741] Recv(010): 06 10 04 21 00 0A 04 17 00 00
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.742] Recv(021): 06 10 04 20 00 15 04 17 00 00 29 00 BC D0 22 14 08 00 01 00 80
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.742] Send(004): 04 17 00 00
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.742] Recv L_Data low from 2.2.20 to 1/0/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 9 [ 4:ipt:192.168.178.57 14.742] Enqueue L_Data low from 2.2.20 to 1/0/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 3 [ 3:layer3             14.742] RecvData L_Data low from 2.2.20 to 1/0/0 hops: 04 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 8 [ 2:mcast:knxd         14.742] Send_Route L_Data low from 2.2.20 to 1/0/0 hops: 04 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 1 [ 2:mcast:knxd         14.742] Send(011): 29 00 BC C0 22 14 08 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.742] Send(010): 06 10 04 21 00 0A 04 17 00 00
knxd: Layer 0 [ 2:mcast:knxd         14.742] Send(017): 06 10 05 30 00 11 29 00 BC C0 22 14 08 00 01 00 80
knxd: Layer 0 [ 2:mcast:knxd         14.742] Dropped(017): 06 10 05 30 00 11 29 00 BC C0 22 14 08 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.962] Recv(021): 06 10 04 20 00 15 04 17 01 00 29 00 BC E0 11 34 29 00 01 00 80
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.962] Send(004): 04 17 01 00
knxd: Layer 1 [ 4:ipt:192.168.178.57 14.962] Recv L_Data low from 1.1.52 to 5/1/0 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 9 [ 4:ipt:192.168.178.57 14.962] Enqueue L_Data low from 1.1.52 to 5/1/0 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 3 [ 3:layer3             14.962] RecvData L_Data low from 1.1.52 to 5/1/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 8 [ 2:mcast:knxd         14.962] Send_Route L_Data low from 1.1.52 to 5/1/0 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 1 [ 2:mcast:knxd         14.962] Send(011): 29 00 BC D0 11 34 29 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 14.962] Send(010): 06 10 04 21 00 0A 04 17 01 00
knxd: Layer 0 [ 2:mcast:knxd         14.962] Send(017): 06 10 05 30 00 11 29 00 BC D0 11 34 29 00 01 00 80
knxd: Layer 0 [ 2:mcast:knxd         14.962] Dropped(017): 06 10 05 30 00 11 29 00 BC D0 11 34 29 00 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 15.061] Recv(021): 06 10 04 20 00 15 04 17 02 00 29 00 BC E0 11 34 29 01 01 00 80
knxd: Layer 1 [ 4:ipt:192.168.178.57 15.061] Send(004): 04 17 02 00
knxd: Layer 1 [ 4:ipt:192.168.178.57 15.061] Recv L_Data low from 1.1.52 to 5/1/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 9 [ 4:ipt:192.168.178.57 15.061] Enqueue L_Data low from 1.1.52 to 5/1/1 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 3 [ 3:layer3             15.061] RecvData L_Data low from 1.1.52 to 5/1/1 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 8 [ 2:mcast:knxd         15.061] Send_Route L_Data low from 1.1.52 to 5/1/1 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00 
knxd: Layer 1 [ 2:mcast:knxd         15.061] Send(011): 29 00 BC D0 11 34 29 01 01 00 80
knxd: Layer 0 [ 4:ipt:192.168.178.57 15.061] Send(010): 06 10 04 21 00 0A 04 17 02 00
knxd: Layer 0 [ 2:mcast:knxd         15.061] Send(017): 06 10 05 30 00 11 29 00 BC D0 11 34 29 01 01 00 80
knxd: Layer 0 [ 2:mcast:knxd         15.061] Dropped(017): 06 10 05 30 00 11 29 00 BC D0 11 34 29 01 01 00 80
knxd: Layer 8 [ 6:inet               21.190] New Connection
knxd: Layer 8 [ 6:inet               21.190] ClientConnection Init
knxd: Layer 3 [ 3:layer3             21.190] Allocate: falling back to 2.2.19
knxd: Layer 8 [ 9:inet               21.190] SendMessage(002): 00 04
```

**Comment by smurfix** [comment]
On 12.01.2017 15:42, JoeRu wrote:
> this is the output of knxd - not really any news
Ah. I think I see it. Give it more than one client address (-E 2.2.20:10
or whatever is free on your bus).

I'll have to check the code why the old address didn't get released – it
said that it did, in the log you posted.

-- 
-- Matthias Urlichs

**Comment by thelsing** [comment]
Is the ft12 driver ready for testing?

**Comment by smurfix** [comment]
On 12.01.2017 19:09, thelsing wrote:
>
> Is the ft12 driver ready for testing?
>
Yes. There's (almost) no difference between that and ft12cemi, which has
been confirmed to work.

-- 
-- Matthias Urlichs

**Comment by thelsing** [comment]
I had the same problem ( Connect failed: Connection reset by peer). 
With "-E 2.2.20:10" knxtool groupswrite worked fine.

**Comment by JoeRu** [comment]
can confirm "-E 2.2.20:10" works - connection errors in the follow up.
👍 
ETS4 programming EIBnetIP did not work - but - i guess thats "Jammern auf hohem Niveau"...
Because - EIBnetRoute do work... no idea whatsoever...

**Comment by ctr49** [comment]
Not sure if this an issue with the libev branch or general behavior as I never used -E before. Is it expected that addresses are not sticky but rather cycled through? I.e. I use -E 1.1.241:8 then the first request leaves with 1.1.249, the second from 1.1.248 and so on. All requests came in on the same socket.
Another thing that I observed that I did not see with eibd/pthsem before is in combination with eibread-cgi (and obviously Cometvisu). I just use about 50 different GAs in the CV config and when I access CV I can also see that "r" is just requested with those listening addresses (48 times a=x/x/), but using the busmonitor I can see requests being made for *every* GA, starting at 0/0/0 and counting up. This continues even when no further "r" request is made, only a restart of knxd stops the query storm.

**Comment by smurfix** [comment]
On 13.01.2017 11:44, Christian Tramnitz wrote:
>
> Not sure if this an issue with the libev branch or general behavior as
> I never used -E before. Is it expected that addresses are not sticky
> but rather cycled through? I.e. I use -E 1.1.241:8 then the first
> request leaves with 1.1.249, the second from 1.1.248 and so on. All
> requests came in on the same socket.
>
No, addresses should be per connection. Are you sure that the client
didn't open a new socket?
>
> Another thing that I observed that I did not see with eibd/pthsem
> before is in combination with eibread-cgi (and obviously Cometvisu). I
> just use about 50 different GAs in the CV config and when I access CV
> I can also see that "r" is just requested with those listening
> addresses (48 times a=x/x/), but using the busmonitor I can see
> requests being made for /every/ GA, starting at 0/0/0 and counting up.
> This continues even when no further "r" request is made, only a
> restart of knxd stops the query storm.
>
eibread-cgi enumerates the bus when it gets started with an offset of
zero. That's been in the code for ages, but maybe it just didn't work
before. :-P

I'll disable that code; it's not very useful to wait 18+ hours for bus
enumeration (one request per second, over 65535 possible addresses …).

-- 
-- Matthias Urlichs

**Comment by ctr49** [comment]
> No, addresses should be per connection. Are you sure that the client
didn't open a new socket?

Yes, according to lsof/netstat the client (yawgd, a wiregate clone used to run some old plugins) was using the same socket all the time.

**Comment by smurfix** [comment]
This test program, with current master, works correctly.

if the problem persists, please provide a server trace.
```
#include "common.h"

int
main (int ac, char *ag[])
{
  int len;
  EIBConnection *con;
  eibaddr_t dest;
  uchar buf[3] = { 0, 0x80 };

  if (ac != 6)
    die ("usage: %s url eibaddr val addr2 val2", ag[0]);
  con = EIBSocketURL (ag[1]);
  if (!con)
    die ("Open failed");

  dest = readgaddr (ag[2]);
  buf[1] |= readHex (ag[3]) & 0x3f;
  if (EIBOpenT_Group (con, dest, 1) == -1)
    die ("Connect failed");
  len = EIBSendAPDU (con, 2, buf);
  if (len == -1)
    die ("Request failed");
  printf ("Send request\n");
  EIBReset (con);

  dest = readgaddr (ag[4]);
  buf[1] |= readHex (ag[5]) & 0x3f;
  if (EIBOpenT_Group (con, dest, 1) == -1)
    die ("Connect2 failed");
  len = EIBSendAPDU (con, 2, buf);
  if (len == -1)
    die ("Request2 failed");
  printf ("Send request2\n");
  EIBReset (con);

  EIBClose (con);
  return 0;
}

```

**Comment by smurfix** [comment]
Closing due to lack of feedback. Please re-open when appropriate.
