### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by tru7** [knxd/knxd#25]
Forgive me, I don't know if it's important or not nor if it's the right time to do it now: I'm always a little insecure about the many compiler warnings. Here is the recent list from my compiler gcc 4.8.2, at least some seem to be unclean coding:
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
../../../src/client/def/opengroupsocket.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentbroadcast.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentgroup.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentindividual.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opengroupsocket.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentbroadcast.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentgroup.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentindividual.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
trace.cpp:32:12: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
trace.cpp:43:65: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
ft12.cpp:244:23: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:259:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:269:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:279:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:557:21: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:592:21: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
knxtool.c:212:7: warning: format not a string literal and no format arguments [-Wformat-security]
knxtool.c:214:7: warning: format not a string literal and no format arguments [-Wformat-security]

**Comment by timowi** [comment]
> cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]

Can be safely ignored. Just a compiler option not used by C code.

> ../../../src/client/def/opentindividual.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]

Looks like a bug in client bindings generation. But is no problem. Extra args are just ignored.

> trace.cpp:32:12: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]

‘unsigned int’ and ‘long unsigned int’ are the same on most platforms. On some embedded this may be a problem. So this should be fixed.

> ft12.cpp:244:23: warning: ignoring return value of ‘ssize_t write(int, const void, size_t)’, declared with attribute warn_unused_result [-Wunused-result]

This is missing error handling. There are many problems like this in the code. The warning can be ignored for now.

> knxtool.c:212:7: warning: format not a string literal and no format arguments [-Wformat-security]

This is no problem. Just bad code style. printf(str) should be printf("%s", str).

**Comment by Makki1** [comment]
It's good to have an issue for that (which should stay open!) as it looks nasty, but I agree: it's nothing critical in current stage.
Though, minor issues (like bad coding style pointed out by timo) should be fixed directly.

**Comment by tru7** [comment]
@Makki1 and @timowi that's fine with me.

**Comment by p3root** [comment]
I have started a new branch for this, https://github.com/Makki1/knxd/tree/compiler-warnings
The printf issues, in knxtool.c are fixed

**Comment by tru7** [comment]
Good try, but you missed the only two bad ones on lines 212 and 214. Besides those two, you changed most of the other printf statements but not all. Any you may also take care of some indents.

**Comment by p3root** [comment]
Thanks, easy to oversee something. I also fixed the "die()" calls. If somebody finds another one, feel free to fix it.

**Comment by tru7** [comment]
Are you sure about your changes on lines 212 and 214? I think it' wrong but I'm no real coder. I think before the argument was a pointer to a sting to be printed, now you print a single character.
Also I'm not sure about the die() call, but I don't know this function, but can you just change from one argument to two??

**Comment by p3root** [comment]
@tru7 Thanks, you're right. I'll change it.

```c
die (const char *msg, ...) {
  va_list ap;
  va_start (ap, msg);
  vprintf (msg, ap);
  printf ("%s", "\n");
  va_end (ap);

  exit (1);
}
```
The die() call is the same as printf. You have an variable argument list. And the call gets forwared to vprintf() which gets also called by printf in the implementation. Therefore this is right.

**Comment by timowi** [comment]
unfortunately you got the printf() thing wrong. Sorry for the additional work.

printf("Some Text\n") is perfectly fine.

It's all about printing 'char arrays' directly.

char * text = "Variable String";
printf(text);

is the only problem. Here there may be a format specifier (%s, %...) in the variable and the compiler cannot check for that. The function does not know about the parameters. So they cannot be checked. Mismatched format specifiers may lead to crashes (It's just read from stack and interpreted as pointer for example). Therefor it's agreed to write the above as 

char * text = "Variable String";
printf("%s", text);

Here it makes no difference whats in 'text'.

**Comment by RichiH** [comment]
@p3root any update on this? Getting rid of warnings will help track down actual errors when they occur.

**Comment by smurfix** [comment]
Are there still any warnings? My build doesn't have any, other than the "ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:" one which I removed in commit 6da0d8c.

**Comment by tru7** [comment]
Are you talking about knxd/master? Yes the warnings are all still there on my Ubuntu 14.04.2:

cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]
../../../src/client/def/opengroupsocket.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentbroadcast.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentgroup.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentindividual.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opengroupsocket.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentbroadcast.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentgroup.inc:36:1: warning: too many arguments for format [-Wformat-extra-args]
../../../src/client/def/opentindividual.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
trace.cpp:32:12: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
trace.cpp:43:65: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
ft12.cpp:244:23: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:259:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:269:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:279:20: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:557:21: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
tpuartserial.cpp:592:21: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
knxtool.c:212:7: warning: format not a string literal and no format arguments [-Wformat-security]
knxtool.c:214:7: warning: format not a string literal and no format arguments [-Wformat-security]

**Comment by smurfix** [comment]
On 19.05.2015 21:49, Othmar Truniger wrote:
>
> Are you talking about knxd/master? Yes the warnings are all still
> there on my Ubuntu 14.04.2:
>
You talked me into it.
>
> cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++
> but not for C [enabled by default]
>
I do not understand this error. configure.ac explicitly adds -fno_rtti
to CXXFLAGS, not CFLAGS, so it should not be applied to C source.
>
> ../../../src/client/def/opengroupsocket.inc:37:1: warning: too many
> arguments for format [-Wformat-extra-args]
>
I do not understand this error. I have looked at all the EIBC_ASYNC
macros and didn't see any problem.
Can you tell me which command this is?

In any case, I added -Wall and -Wextra to .travis.yml, compiled the
thing, fixed a whole heap of warnings, and found a couple of bugs.

One warning is left unfixed because I don't have any documentation about
the FT1.2 backend. I only found a request for documentation in the forum
… from 2007 … does anybody even use that any more?

-- 
-- Matthias Urlichs

**Comment by RichiH** [comment]
Do you have any custom settings for your build chain?

Ideally, compile under a new test user with a completely new clone of the
repo.

Richard

Sent by mobile; excuse my brevity.

**Comment by smurfix** [comment]
I'm using Debian Jessie. No build chain surprises here.

Please send not just the error but also the command line (as reported by "make") used to produce them.
That's far quicker to do for a problem like this than for me to set up a new Ubuntu VM.

**Comment by RichiH** [comment]
@smurfix sorry, I meant to ask @tru7 if he has any special settings

**Comment by tru7** [comment]
@RichiH : I'm happy to provide more details on the warnings. To the best of my knowlege I don't use any special settings for the compiler. Also for every run I start with a new clone. Then just the standard "./bootstrap.sh", "./configure <some enable params>", "make" and "make install".

In Makefile:
CFLAGS = -g -O2
CXXFLAGS = -g -O2 -fno-rtti -fno-exceptions

Example 1:
if g++ -DHAVE_CONFIG_H -I. -I../../..  -I../../../src/include -I../../../src/client -I../../../src/client   -g -O2 -fno-rtti -fno-exceptions -D__cplusplus -MT EIBConnection.post -MD -MP -MF ".deps/EIBConnection.Tpo" -E -P -x c -O0 -o EIBConnection.post EIBConnection.pre; \
        then mv -f ".deps/EIBConnection.Tpo" ".deps/EIBConnection.Po"; else rm -f ".deps/EIBConnection.Tpo"; exit 1; fi
cc1: warning: command line option ‘-fno-rtti’ is valid for C++/ObjC++ but not for C [enabled by default]

Example 2:
gcc -DHAVE_CONFIG_H -I. -I../../..  -I../../../src/include -I../../../src/client -I../../../src/client   -g -O2 -MT gen.o -MD -MP -MF .deps/gen.Tpo -c -o gen.o gen.c
In file included from ../../../src/client/def/all.lst:73:0,
                 from gen.c:36:
../../../src/client/def/opengroupsocket.inc: In function ‘main’:
../../../src/client/def/opengroupsocket.inc:37:1: warning: too many arguments for format [-Wformat-extra-args]
 EIBC_ASYNC (EIBOpen_GroupSocket, ARG_BOOL (write_only, ARG_NONE),
 ^

Example 3:
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common -I/sw/pkgs/pthsem-2.0.8/include   -g -O2 -fno-rtti -fno-exceptions -MT trace.o -MD -MP -MF .deps/trace.Tpo -c -o trace.o trace.cpp
trace.cpp: In member function ‘virtual void Trace::TracePacketUncond(int, void*, const char*, int, const uchar*)’:
trace.cpp:32:12: warning: format ‘%X’ expects argument of type ‘unsigned int’, but argument 3 has type ‘long unsigned int’ [-Wformat=]
    msg, Len);
            ^

Example 4:
g++ -DHAVE_CONFIG_H -I. -I../..  -I../../src/libserver -I../../src/common -I../../src/usb -I/sw/pkgs/pthsem-2.0.8/include -I/usr/include/libusb-1.0     -g -O2 -fno-rtti -fno-exceptions -MT ft12.o -MD -MP -MF .deps/ft12.Tpo -c -o ft12.o ft12.cpp
ft12.cpp: In member function ‘virtual void FT12LowLevelDriver::Run(pth_sem_t*)’:
ft12.cpp:244:23: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     write (fd, &c1, 1);
                       ^

Example 5:
gcc -DHAVE_CONFIG_H -I. -I../..  -I../../src/include -I../../src/common   -g -O2 -MT knxtool.o -MD -MP -MF .deps/knxtool.Tpo -c -o knxtool.o knxtool.c
knxtool.c: In function ‘main’:
knxtool.c:212:7: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (ag[3]);
       ^
knxtool.c:214:7: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (ag[4]);
       ^

**Comment by smurfix** [comment]
On 20.05.2015 20:38, Othmar Truniger wrote:
> g++ -DHAVE_CONFIG_H -I. -I../../.. -I../../../src/include
> -I../../../src/client -I../../../src/client -g -O2 -fno-rtti
> -fno-exceptions -D__cplusplus -MT EIBConnection.post -MD -MP -MF
> ".deps/EIBConnection.Tpo" -E -P -x c -O0 -o EIBConnection.post
> EIBConnection.pre
It'd make more sense to use the C preprocessor to pereprocess files,
instead of the C++ compiler …

Anyway: fixes checked in and uploaded.

-- 
-- Matthias Urlichs

**Comment by smurfix** [comment]
Should be all fixed by now. Please re-open if you still see any errors or warnings.
