### ISSUE TITLE
NCN5120 Driver not found

### ISSUE THREAD

**Issue by Chaeben** [knxd/knxd#342]
Hello,

I am trying to use the backend for the ncn5120. I tried the backend for the tpuarts and it works flawless. But as soon as I edit the etc/knxd.conf file in a way to use the ncn5120 my knxd gets into error mode.
The KNXD_OPTS are these:

> KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -DTRS -u /tmp/eib -b ncn5120:dev/ttyKNX1"

and after the restart of knxd i can read this errorlog with the command

> journalctl -xe

and I get this

> -- Unit knxd.service has begun starting up.
Jun 11 09:23:37 raspberrypi knxd[1068]: E00000055: [ 1:main] Driver 'ncn5120' not found.
Jun 11 09:23:37 raspberrypi knxd[1068]: E00000055: [ 1:main] Section 'B.ncn5120' has no known server nor driver.
Jun 11 09:23:37 raspberrypi knxd[1068]: F00000000: [ 1:main] Error setting up the KNX router.
Jun 11 09:23:37 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 11 09:23:37 raspberrypi systemd[1]: Failed to start KNX Daemon.
-- Subject: Unit knxd.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit knxd.service has failed.
--
-- The result is failed.
Jun 11 09:23:37 raspberrypi systemd[1]: knxd.service: Unit entered failed state.
Jun 11 09:23:37 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.

I appriciate anny kind of help.

I will give further Informations if needed.

Best Regards

Chaeben

**Comment by smurfix** [comment]
Thanks for the bug report.
Should be fixed in v0.14.25.

**Comment by Chaeben** [comment]
Hello,

I installed the new version, but i still get the same error.

Best regards

Chaeben

**Comment by Ks89** [comment]
In this file [contrib/gentoo/sys-apps/knxd/knxd-9999.ebuild](https://github.com/knxd/knxd/commit/203d1ac53c95c882b0152cbd8245517090e87d50) I saw that there is a new param to build knxd with NCN5120 support, but not in https://github.com/knxd/knxd/blob/master/configure.ac

The option `--enable-ncn5120` is unknown.  Is it required to properly use knxd with ncn5120?

**Comment by lonpr** [comment]
Hello! 
I have version 0.14-25 and the same error:

12:42:10 raspberrypi knxd[764]: E00000089: [ 1:main] Driver 'ncn5120' not found.
12:42:10 raspberrypi knxd[764]: E00000091: [ 1:main] Section 'B.ncn5120' has no known server nor driver.
12:42:10 raspberrypi knxd[764]: F00000109: [ 1:main] Error setting up the KNX router.
12:42:10 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
12:42:10 raspberrypi systemd[1]: Failed to start KNX Daemon.

Is there a solution to this problem?

**Comment by smurfix** [comment]
Sorry, that fell through the cracks of my non-existing spare time. Will fix ASAP.

**Comment by lonpr** [comment]
Thank you!

**Comment by smurfix** [comment]
Should be resolved with current master. Please test.

**Comment by lonpr** [comment]
ok, it's work. Is it possible to change the speed from 38400 to 19200, does my shild have a speed of only 19200?

**Comment by lonpr** [comment]
setting: KNXD_OPTS="-e 0.0.1 -E 0.0.2:8 -u /tmp/eib -f -t1023 -b ncn5120:/dev/ttyKNX1:19200"
and:
11:10:54 raspberrypi knxd[2146]: Layer 0 [18:B.ncn5120/log       0.005] Recv(001): 03
11:10:54 raspberrypi knxd[2146]: Layer 8 [15:B.ncn5120/LowF      0.005] RESET_ACK
11:10:54 raspberrypi knxd[2146]: Layer 8 [15:B.ncn5120/LowF      0.005] state: in_reset > in_setaddr
11:10:54 raspberrypi knxd[2146]: Layer 8 [15:B.ncn5120/LowF      0.005] addr zero: in_reset > in_getstate
11:10:54 raspberrypi knxd[2146]: Layer 0 [15:B.ncn5120/LowF      0.005] Send GetState 02
 11:10:54 raspberrypi knxd[2146]: Layer 0 [18:B.ncn5120/log       0.005] Send(001): 02
 11:10:54 raspberrypi knxd[2146]: Layer 0 [18:B.ncn5120/log       0.008] Recv(001): 07
 11:10:54 raspberrypi knxd[2146]: Layer 8 [15:B.ncn5120/LowF      0.008] State: 07
 11:10:54 raspberrypi knxd[2146]: Layer 8 [15:B.ncn5120/LowF      0.008] state: in_getstate > is_online
 11:10:54 raspberrypi knxd[2146]: Layer 0 [16:B.ncn5120/log       0.008] Started
11:10:54 raspberrypi knxd[2146]: Layer 5 [13:B.ncn5120/Conn      0.008] >up => up
11:10:54 raspberrypi knxd[2146]: Layer 4 [13:B.ncn5120/Conn      0.008] up
11:10:54 raspberrypi knxd[2146]: Layer 5 [13:B.ncn5120/Conn      0.008] Started
11:10:54 raspberrypi knxd[2146]: Layer 0 [16:B.ncn5120/log       0.008] send_Next
11:10:54 raspberrypi knxd[2146]: Layer 6 [13:B.ncn5120/Conn      0.008] sendNext called, send_more set
 
but, if send commаnd in knx tp line -> off in group addres 10/0/2: 

11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.976] Recv(008): 9C FF FF 50 02 E1 00 80
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.976] state: wait > wait_more
11:53:41 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       132.976] Known Addr 10/0/2: no
11:53:41 raspberrypi knxd[2520]: Layer 0 [15:B.ncn5120/LowF      132.976] SendAck 10
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.976] Send(001): 10
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.979] Recv(001): 50
11:53:41 raspberrypi knxd[2520]: Layer 1 [15:B.ncn5120/LowF      132.979] RecvLP(009): 9C FF FF 50 02 E1 00 80 50
11:53:41 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       132.979] Recv L_Data (repeated) low from 15.15.255 to 10/0/2 hops: 06 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.979] state: wait_more > wait
11:53:41 raspberrypi knxd[2520]: Layer 6 [13:B.ncn5120/Conn      132.979] sending, send_more clear
11:53:41 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       132.979] Send L_Data low from 15.15.255 to 10/0/2 hops: 05 T_DATA_XXX_REQ A_GroupValue_Write (small) 00
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.979] Send(018): 80 BC 81 FF 82 FF 83 50 84 02 85 D1 86 00 87 80 48 40
11:53:41 raspberrypi knxd[2520]: Layer 6 [13:B.ncn5120/Conn      132.979] still waiting
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.988] Recv(008): 13 17 17 17 17 17 17 17
 11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.988] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.988] State: 17
 11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.988] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.988] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.988] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
 11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.989] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
 11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.989] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       132.991] Recv(001): 17
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      132.991] State: 17
11:53:41 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x17
11:53:41 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:41 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       133.022] Recv(001): 03
11:53:41 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      133.022] spurious RESET_ACK
11:53:43 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      134.981] send timeout: retry
11:53:43 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       134.981] Send(018): 80 9C 81 FF 82 FF 83 50 84 02 85 D1 86 00 87 80 48 60
11:53:43 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       134.993] Recv(001): 27
 11:53:43 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      134.993] State: 27
11:53:43 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x27
11:53:43 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:45 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      136.983] send timeout: retry
11:53:45 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       136.983] Send(018): 80 9C 81 FF 82 FF 83 50 84 02 85 D1 86 00 87 80 48 60
11:53:45 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       136.995] Recv(001): 27
11:53:45 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      136.995] State: 27
11:53:45 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x27
11:53:45 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:47 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      138.985] send timeout: retry
 11:53:47 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       138.985] Send(018): 80 9C 81 FF 82 FF 83 50 84 02 85 D1 86 00 87 80 48 60
 11:53:47 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       138.997] Recv(001): 27
 11:53:47 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      138.997] State: 27
11:53:47 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x27
11:53:47 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:49 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      140.987] send timeout: retry
11:53:49 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       140.987] Send(018): 80 9C 81 FF 82 FF 83 50 84 02 85 D1 86 00 87 80 48 60
11:53:49 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       140.999] Recv(001): 27
11:53:49 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      140.999] State: 27
11:53:49 raspberrypi knxd[2520]: W00000116: [15:B.ncn5120] TPUART error state x27
11:53:49 raspberrypi knxd[2520]: W00000117: [15:B.ncn5120] TPUART state wait should not happen
11:53:51 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      142.981] state: wait > wait_keepalive
11:53:51 raspberrypi knxd[2520]: Layer 0 [15:B.ncn5120/LowF      142.981] Send GetState 02
11:53:51 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       142.981] Send(001): 02
11:53:51 raspberrypi knxd[2520]: E00000055: [13:B.ncn5120] Driver timed out trying to send (B.ncn5120)
11:53:51 raspberrypi knxd[2520]: Layer 5 [13:B.ncn5120/Conn      142.981] up => down/error
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      142.981] up/error
11:53:51 raspberrypi knxd[2520]: Layer 5 [13:B.ncn5120/Conn      142.981] Stopping
 11:53:51 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       142.981] Stop
11:53:51 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       142.981] Stop
11:53:51 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       143.010] Stopped
11:53:51 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      143.010] state: wait_keepalive > new
11:53:51 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       143.010] Stopped
11:53:51 raspberrypi knxd[2520]: Layer 5 [13:B.ncn5120/Conn      143.010] up/error => down
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      143.010] down/error
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      143.010] is down
11:53:51 raspberrypi knxd[2520]: F00000105: [13:B.ncn5120] Link down, terminating
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      143.010] Stopping
11:53:51 raspberrypi knxd[2520]: Layer 5 [13:B.ncn5120/Conn      143.010] down/error => >down
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      143.010] down/error
11:53:51 raspberrypi knxd[2520]: Layer 4 [13:B.ncn5120/Conn      143.010] is down
11:53:51 raspberrypi knxd[2520]: E00000043: [15:B.ncn5120] send timeout: too many retries
11:53:51 raspberrypi knxd[2520]: Layer 8 [15:B.ncn5120/LowF      143.010] state: new > error
 11:53:51 raspberrypi knxd[2520]: Layer 0 [16:B.ncn5120/log       143.010] Closing
11:53:51 raspberrypi knxd[2520]: Layer 2 [15:B.ncn5120/LowF      143.010] Close
11:53:51 raspberrypi knxd[2520]: Layer 0 [18:B.ncn5120/log       143.010] Closing
11:53:51 raspberrypi knxd[2520]: Layer 2 [17:B.ncn5120/NCN_ser   143.010] Close
11:53:51 raspberrypi systemd[1]: knxd.service: Main process exited, code=exited, status=1/FAILURE
 11:53:51 raspberrypi systemd[1]: knxd.service: Unit entered failed state.
11:53:51 raspberrypi systemd[1]: knxd.service: Failed with result 'exit-code'.
